# Generated by Django 4.1.2 on 2022-12-29 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_addresslist_order_payment_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='order_placed', max_length=20),
        ),
        migrations.DeleteModel(
            name='Addresslist',
        ),
        migrations.DeleteModel(
            name='Order_details',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
