# Generated by Django 4.1.2 on 2022-12-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_order_detail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.order'),
        ),
    ]
